#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
quadrant_topology.py
Build a quadrant-based network topology, draw it, and emit rippled.cfg files.

- Central Hubs cluster (5 hubs) near origin.
- 4 subnets, each in its own quadrant, each with a local hub and validators.
- Validators connect ONLY to their local hub + a few validator↔validator edges.
- Each local subnet hub connects to exactly ONE central hub.
- Writes one rippled.cfg per node with [ips_fixed] neighbors (names only).

Usage:
  python3 quadrant_topology.py -c config.json -o star.png --cfg-out cfg/
"""

import argparse, json, math, os, random
from typing import Dict, List, Tuple, Iterable, Set

import matplotlib.pyplot as plt
import networkx as nx
from matplotlib.patches import Rectangle, FancyBboxPatch

# --------------------------- helpers ---------------------------

def ring(n: int, r: float, start_deg: float = -90.0) -> List[Tuple[float, float]]:
    pts = []
    for i in range(n):
        ang = math.radians(start_deg + 360.0 * i / n)
        pts.append((r*math.cos(ang), r*math.sin(ang)))
    return pts

def rect_from_points(points: Iterable[Tuple[float, float]], pad: float = 0.5) -> Tuple[float, float, float, float]:
    xs = [p[0] for p in points]; ys = [p[1] for p in points]
    xmin, xmax = min(xs)-pad, max(xs)+pad
    ymin, ymax = min(ys)-pad, max(ys)+pad
    return xmin, ymin, xmax-xmin, ymax-ymin

def write_cfg(node: str, peers: Iterable[str], outdir: str):
    os.makedirs(outdir, exist_ok=True)
    with open(os.path.join(outdir, f"{node}.cfg"), "w", encoding="utf-8") as f:
        f.write("# Autogenerated\n[ips_fixed]\n")
        for p in sorted(set(peers)):
            if p != node:
                f.write(f"{p}\n")

# --------------------------- generator ---------------------------

def build_topology(cfg: Dict) -> Tuple[nx.Graph, Dict[str, Tuple[float,float]], Dict[str, Dict]]:
    rnd = random.Random(cfg.get("seed", 42))

    # counts
    num_central = 5
    num_subnets = 4
    vps = cfg.get("validators_per_subnet", [7,6,6,6])
    if isinstance(vps, int):
        validators_per_subnet = [vps]*num_subnets
    else:
        validators_per_subnet = vps

    # geometry (user-tunable units)
    hub_ring_r = float(cfg.get("hub_ring_radius", 2.2))
    quad_offset = float(cfg.get("quadrant_offset", 9.0))  # distance of subnet hubs from origin
    val_radius = float(cfg.get("validator_ring_radius", 2.6))
    jitter = float(cfg.get("validator_jitter", 0.35))
    pastel = ["#e8f5e9","#e3f2fd","#fff8e1","#f3e5f5"]

    intra_min = int(cfg.get("intra_min_degree", 1))
    intra_max = int(cfg.get("intra_max_degree", 3))
    hub_connect_fraction = float(cfg.get("hub_connect_fraction", 1.0))

    G = nx.Graph()
    pos: Dict[str, Tuple[float, float]] = {}
    clusters: Dict[str, Dict] = {}  # name -> {label, color, nodes}

    # ----- central hubs cluster -----
    hubs = [f"Hub{i}_c" for i in range(1, num_central+1)]
    for (x,y), n in zip(ring(num_central, hub_ring_r), hubs):
        pos[n] = (x,y)
        G.add_node(n, kind="hub_c")
    # fully connect central hubs
    for i in range(len(hubs)):
        for j in range(i+1, len(hubs)):
            G.add_edge(hubs[i], hubs[j])

    clusters["hubs"] = {"label":"Hubs", "color":"#eeeeee", "nodes":hubs}

    # ----- subnet clusters in 4 quadrants -----
    quad_centers = [(-quad_offset, quad_offset),   # NW
                    ( quad_offset, quad_offset),   # NE
                    ( quad_offset,-quad_offset),   # SE
                    (-quad_offset,-quad_offset)]   # SW

    val_counter = 1
    local_hubs: List[str] = []

    for s in range(num_subnets):
        cname = f"s{s+1}"
        color = pastel[s % len(pastel)]
        cx, cy = quad_centers[s]
        local = f"s{s+1}_hub"
        local_hubs.append(local)
        pos[local] = (cx, cy)
        G.add_node(local, kind="hub_s")
        # validators around local hub
        nvals = validators_per_subnet[s]
        vals: List[str] = []
        for k, (dx,dy) in enumerate(ring(nvals, val_radius, start_deg=20+90*s), start=1):
            jx = rnd.uniform(-jitter, jitter)
            jy = rnd.uniform(-jitter, jitter)
            vid = f"val{val_counter:02d}"
            val_counter += 1
            pos[vid] = (cx+dx+jx, cy+dy+jy)
            G.add_node(vid, kind="validator", fill=color)
            vals.append(vid)

        # edges: local hub to validators (subset by fraction)
        for v in vals:
            if rnd.random() <= hub_connect_fraction:
                G.add_edge(local, v)

        # sparse validator↔validator edges (degree in [min,max])
        target = {v: rnd.randint(intra_min, intra_max) for v in vals}
        tries, max_tries = 0, nvals*nvals*3
        while tries < max_tries:
            need = [v for v in vals if target[v] > 0]
            if not need: break
            u = rnd.choice(need)
            w = rnd.choice([x for x in vals if x != u])
            if not G.has_edge(u,w):
                G.add_edge(u,w)
                target[u] -= 1; target[w] -= 1
            tries += 1

        # connect this subnet hub to ONE central hub
        chosen = rnd.choice(hubs)
        G.add_edge(local, chosen)

        # record cluster
        clusters[cname] = {"label": f"Subnet {s+1} ({nvals})", "color": color, "nodes":[local]+vals}

    return G, pos, clusters

# --------------------------- drawing ---------------------------

def draw_topology(G, pos, clusters, out_png):
    import matplotlib.pyplot as plt
    from matplotlib.patches import Rectangle, FancyBboxPatch
    import networkx as nx

    fig, ax = plt.subplots(figsize=(10,10))
    ax.set_aspect("equal"); ax.axis("off")

    # 1) cluster boxes behind everything
    def rect_from_points(points, pad=0.5):
        xs = [p[0] for p in points]; ys = [p[1] for p in points]
        xmin, xmax = min(xs)-pad, max(xs)+pad
        ymin, ymax = min(ys)-pad, max(ys)+pad
        return xmin, ymin, xmax-xmin, ymax-ymin

    for name, meta in clusters.items():
        pts = [pos[n] for n in meta["nodes"]]
        x,y,w,h = rect_from_points(pts, pad=1.1 if name!="hubs" else 0.9)
        if name == "hubs":
            box = FancyBboxPatch((x,y), w,h, boxstyle="round,pad=0.3,rounding_size=0.3",
                                 linewidth=1.2, edgecolor="black", facecolor="none")
            ax.add_patch(box)
            ax.text(x+w/2, y+h+0.4, meta["label"], ha="center", va="bottom", fontsize=12)
        else:
            rect = Rectangle((x,y), w,h, linewidth=1.1, edgecolor="black", facecolor="none")
            ax.add_patch(rect)
            ax.text(x+w/2, y+h+0.3, meta["label"], ha="center", va="bottom", fontsize=11)

    # 2) edges
    edges = list(G.edges())
    edges_artist = nx.draw_networkx_edges(
        G, pos, edgelist=edges, ax=ax, width=1.0, alpha=0.35, edge_color="#555"
    )
    # Set zorder safely (handles list or single collection)
    try:
        if isinstance(edges_artist, (list, tuple)):
            for coll in edges_artist:
                coll.set_zorder(1)
        elif edges_artist is not None:
            edges_artist.set_zorder(1)
    except Exception:
        pass

    # 3) nodes
    hubs_c = [n for n,d in G.nodes(data=True) if d.get("kind")=="hub_c"]
    hubs_s = [n for n,d in G.nodes(data=True) if d.get("kind")=="hub_s"]
    vals   = [n for n,d in G.nodes(data=True) if d.get("kind")=="validator"]

    hubs_c_artist = nx.draw_networkx_nodes(
        G, pos, nodelist=hubs_c, node_color="#eeeeee", node_shape="8",
        node_size=1100, edgecolors="black", linewidths=1.2, ax=ax
    )
    hubs_s_artist = nx.draw_networkx_nodes(
        G, pos, nodelist=hubs_s, node_color="white", node_shape="o",
        node_size=900, edgecolors="black", linewidths=1.2, ax=ax
    )
    vals_artist = nx.draw_networkx_nodes(
        G, pos, nodelist=vals,
        node_color=[G.nodes[v].get("fill","#e8f5e9") for v in vals],
        node_shape="o", node_size=800, edgecolors="black", linewidths=1.0, ax=ax
    )
    # bump node z-order
    for artist in (hubs_c_artist, hubs_s_artist, vals_artist):
        try:
            if artist is not None:
                artist.set_zorder(2)
        except Exception:
            pass

    # 4) labels
    lbls = {n:(n.replace("_c","").replace("_s","")) for n in hubs_c+hubs_s}
    lbls.update({v:v for v in vals})
    texts = nx.draw_networkx_labels(G, pos, labels=lbls, font_size=9, ax=ax)
    # raise labels
    try:
        for t in texts.values():
            t.set_zorder(3)
    except Exception:
        pass

    # frame
    xs, ys = zip(*pos.values()); pad = 2.0
    ax.set_xlim(min(xs)-pad, max(xs)+pad)
    ax.set_ylim(min(ys)-pad, max(ys)+pad)

    fig.tight_layout()
    if out_png:
        fig.savefig(out_png, dpi=180)
        print(f"Wrote image: {out_png}")
    else:
        plt.show()

# --------------------------- cfg writing ---------------------------

def write_all_cfgs(G: nx.Graph, outdir: str, only_prefix: str = None):
    adj: Dict[str, Set[str]] = {n: set(G.neighbors(n)) for n in G.nodes()}
    count = 0
    for n, peers in adj.items():
        if only_prefix and not n.startswith(only_prefix):
            continue
        write_cfg(n, peers, outdir)
        count += 1
    print(f"Wrote {count} cfg files to {outdir}/")

# --------------------------- CLI ---------------------------

def main():
    ap = argparse.ArgumentParser(description="Quadrant topology drawer + rippled.cfg writer")
    ap.add_argument("-c","--config", help="JSON config (optional)")
    ap.add_argument("-o","--out", help="Output image file (png/svg). Default: star.png", default="star.png")
    ap.add_argument("--cfg-out", help="Directory to write rippled.cfg files")
    ap.add_argument("--only-prefix", help="Only emit cfgs for nodes with this prefix (e.g. 'val')", default=None)
    args = ap.parse_args()

    # defaults
    cfg = {
        "seed": 123,
        "validators_per_subnet": [7,6,6,6],
        "hub_ring_radius": 2.2,
        "quadrant_offset": 9.0,
        "validator_ring_radius": 2.6,
        "validator_jitter": 0.35,
        "intra_min_degree": 1,
        "intra_max_degree": 3,
        "hub_connect_fraction": 1.0
    }
    if args.config:
        with open(args.config, "r", encoding="utf-8") as f:
            cfg.update(json.load(f))

    G, pos, clusters = build_topology(cfg)
    if args.cfg_out:
        write_all_cfgs(G, args.cfg_out, only_prefix=args.only_prefix)
    draw_topology(G, pos, clusters, args.out)

if __name__ == "__main__":
    main()
