"""Account generation and resolution utilities."""

import json
from collections.abc import Iterable
from dataclasses import dataclass
from pathlib import Path

from pydantic import PositiveInt
from pydantic_settings import BaseSettings, SettingsConfigDict

from generate_ledger.crypto_backends import Algorithm, backend_info, get_backend


@dataclass
class Account:
    address: str
    seed: str
    algorithm: str = "secp256k1"  # "ed25519" or "secp256k1"
    # Raw bytes from GPU pipeline — avoids base58 round-tripping for index computation.
    # None when generated by CPU backends (indices computed via base58 decode).
    account_id: bytes | None = None  # 20-byte RIPEMD160(SHA256(pubkey))
    account_root_idx: str | None = None  # SHA512Half(0x0061 + account_id), uppercase hex
    owner_dir_idx: str | None = None  # SHA512Half(0x004F + account_id), uppercase hex

    def __repr__(self):
        return f"Account({self.address}, {self.seed})"

    def __str__(self):
        return f"{self.address}, {self.seed}"


class AccountConfig(BaseSettings):
    model_config = SettingsConfigDict(env_prefix="GL_", env_file=".env")
    num_accounts: PositiveInt = 2
    algo: str = "ed25519"  # "ed25519" or "secp256k1"
    balance: str = str(100_000_000000)  # 100k XRP
    use_gpu: bool = False


def generate_accounts(config: AccountConfig | None = None, *, use_gpu: bool = False) -> list[Account]:
    """
    Generates n accounts (address + seed).

    Uses native crypto backends when available (PyNaCl for ed25519)
    for ~300x speedup over xrpl-py's pure-Python implementation.

    With use_gpu=True and CuPy installed, uses GPU-accelerated batch
    generation for ed25519 (~10x faster than PyNaCl for large batches).
    """
    cfg = config or AccountConfig()
    gpu = use_gpu or cfg.use_gpu
    algo = Algorithm(cfg.algo)
    backend = get_backend(algo, use_gpu=gpu)
    _, name = backend_info(algo, use_gpu=gpu)
    print(f"Generating {cfg.num_accounts} accounts ({cfg.algo}, backend={name}).")

    # Use full GPU generation if available (includes precomputed indices)
    if hasattr(backend, "generate_accounts_full"):
        rows = backend.generate_accounts_full(cfg.num_accounts)
        return [
            Account(addr, seed, algorithm=cfg.algo, account_id=acct_id, account_root_idx=ari, owner_dir_idx=odi)
            for seed, addr, acct_id, ari, odi in rows
        ]
    # Use batch generation if available (GPU backend, no indices)
    if hasattr(backend, "generate_accounts_batch"):
        pairs = backend.generate_accounts_batch(cfg.num_accounts)
        return [Account(address, seed, algorithm=cfg.algo) for seed, address in pairs]

    out: list[Account] = []
    for _ in range(cfg.num_accounts):
        seed, address = backend.generate_account()
        out.append(Account(address, seed, algorithm=cfg.algo))
    return out


def write_accounts_json(accounts: Iterable[tuple[str, str]], path: Path) -> None:
    data = [(a.address, a.seed) for a in accounts]
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2))


def resolve_account_ref(ref: str | None, accounts: list[Account]) -> str | None:
    """
    Resolve an account reference to an address.

    If ref is a digit string (e.g., "0", "1"), treat it as an index into accounts.
    Otherwise, return it as-is (assuming it's an address).
    """
    if ref is None:
        return None
    if ref.isdigit():
        idx = int(ref)
        if 0 <= idx < len(accounts):
            return accounts[idx].address
        raise ValueError(f"Account index {idx} out of range (have {len(accounts)} accounts)")
    return ref


def resolve_account_to_object(ref: str, accounts: list[Account]) -> Account:
    """
    Resolve an account reference to an Account object.

    If ref is a digit string (e.g., "0", "1"), treat it as an index into accounts.
    Otherwise, search by address.
    """
    if ref.isdigit():
        idx = int(ref)
        if 0 <= idx < len(accounts):
            return accounts[idx]
        raise ValueError(f"Account index {idx} out of range (have {len(accounts)} accounts)")

    # Search by address
    for acct in accounts:
        if acct.address == ref:
            return acct
    raise ValueError(f"Account with address '{ref}' not found in accounts list")
