services:
  val0:
    image: rippleci/rippled:latest
    container_name: val0
    hostname: val0
    entrypoint: ["rippled"]
    ports:
      - 5006:5005
      - 6007:6006
    command: ["--ledgerfile", "/ledger.json"]
    healthcheck:
      test: ["CMD", "rippled", "--silent", "ping"]
      start_period: 10s
      interval: 10s
    volumes:
      - ./volumes/val0:/etc/opt/ripple
      - ./ledger.json:/ledger.json
    networks:
      - xrpl_net
  val1:
    image: rippleci/rippled:latest
    container_name: val1
    hostname: val1
    entrypoint: ["rippled"]
    command: ["--net"]
    depends_on:
      val0:
        condition: service_healthy
    volumes:
      - ./volumes/val1:/etc/opt/ripple
      - ./ledger.json:/ledger.json
    networks:
      - xrpl_net
  val2:
    image: rippleci/rippled:latest
    container_name: val2
    hostname: val2
    entrypoint: ["rippled"]
    command: ["--net"]
    depends_on:
      val0:
        condition: service_healthy
    volumes:
      - ./volumes/val2:/etc/opt/ripple
      - ./ledger.json:/ledger.json
    networks:
      - xrpl_net
  val3:
    image: rippleci/rippled:latest
    container_name: val3
    hostname: val3
    entrypoint: ["rippled"]
    command: ["--net"]
    depends_on:
      val0:
        condition: service_healthy
    volumes:
      - ./volumes/val3:/etc/opt/ripple
      - ./ledger.json:/ledger.json
    networks:
      - xrpl_net
  val4:
    image: rippleci/rippled:latest
    container_name: val4
    hostname: val4
    entrypoint: ["rippled"]
    command: ["--net"]
    depends_on:
      val0:
        condition: service_healthy
    volumes:
      - ./volumes/val4:/etc/opt/ripple
      - ./ledger.json:/ledger.json
    networks:
      - xrpl_net
  rippled:
    image: rippleci/rippled:latest
    container_name: rippled
    hostname: rippled
    entrypoint: ["rippled"]
    ports:
      - 5005:5005
      - 6006:6006
    depends_on:
      val0:
        condition: service_healthy
    volumes:
      - ./volumes/rippled:/etc/opt/ripple
    networks:
      - xrpl_net
networks:
  xrpl_net:
    name: xrpl_net
