name: Build and upload

on:
  push:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Environment'
        required: false
        default: 'dev'
        type: choice
        options:
          - dev
          - release
jobs:
  build_package:
    runs-on: ubuntu-latest
    container: ghcr.io/astral-sh/uv:python3.13-bookworm
    # permissions:
    #   id-token: write
    #   contents: read
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: build package
        working-directory: generate_ledger
        run: |
          uv version --bump alpha
          uv build
          uv publish --index testpypi
